### ISSUE TITLE
Crash after eating

### ISSUE THREAD

**Issue by SpittingBull** [Tfarcenim/ClassicBar#3]
Like this mod! Just tried version 0.0.7. Started with hunger down to 45% - ate some bread up to 90%, opened a chest and the game chrashed:

`Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 3
    at tfar.classicbar.ScalingBarHandler.calculateBarHexColor(ScalingBarHandler.java:38)
    at tfar.classicbar.overlays.HealthBarRenderer.renderHealthBar(HealthBarRenderer.java:96)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_977_HealthBarRenderer_renderHealthBar_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
    at net.minecraftforge.client.GuiIngameForge.renderHealth(GuiIngameForge.java:388)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:154)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1420)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 `

**Comment by Tfarcenim** [comment]
Should be fixed in 0.0.8
